import { BuildingDef } from './types';

export const LOCATION_LABEL = 'Sector 47, Gurugram (simulated)';

export const DEFAULT_BUILDINGS: BuildingDef[] = [
  {
    id: 'nova',
    name: 'Nova Tower',
    type: 'office',
    areaM2: 42000,
    baseKw: 80,
    plugKw: 220,
    lightKw: 110,
    hvacRatedKw: 520,
    K: 26,
    tau: 4,
    solarKwp: 500,
    batteryKwh: 400,
    batteryKw: 150,
    evSessionsCount: 28,
    comfortMin: 22,
    comfortMax: 26,
    daylightFraction: 0.6,
    m2PerPerson: 10,
    schedule: { startHour: 7, endHour: 20, is24h: false },
    benchmarkEui: null,
  },
  {
    id: 'horizon',
    name: 'Horizon Mall',
    type: 'retail',
    areaM2: 55000,
    baseKw: 150,
    plugKw: 260,
    lightKw: 240,
    hvacRatedKw: 800,
    K: 28,
    tau: 3,
    solarKwp: 300,
    batteryKwh: 0,
    batteryKw: 0,
    evSessionsCount: 40,
    comfortMin: 22,
    comfortMax: 26,
    daylightFraction: 0.1,
    m2PerPerson: 4,
    schedule: { startHour: 9, endHour: 22, is24h: false },
    benchmarkEui: null,
  },
  {
    id: 'citycare',
    name: 'CityCare Hospital',
    type: 'hospital',
    areaM2: 28000,
    baseKw: 150,
    plugKw: 100,
    lightKw: 60,
    hvacRatedKw: 360,
    K: 26,
    tau: 6,
    solarKwp: 220,
    batteryKwh: 600,
    batteryKw: 200,
    evSessionsCount: 14,
    comfortMin: 22,
    comfortMax: 25,
    daylightFraction: 0.3,
    m2PerPerson: 15,
    schedule: { startHour: 0, endHour: 24, is24h: true },
    benchmarkEui: null,
  },
  {
    id: 'campus',
    name: 'Campus Block D',
    type: 'university',
    areaM2: 30000,
    baseKw: 60,
    plugKw: 120,
    lightKw: 60,
    hvacRatedKw: 260,
    K: 26,
    tau: 5,
    solarKwp: 800,
    batteryKwh: 500,
    batteryKw: 200,
    evSessionsCount: 30,
    comfortMin: 22,
    comfortMax: 27,
    daylightFraction: 0.6,
    m2PerPerson: 5,
    schedule: { startHour: 7, endHour: 19, is24h: false },
    benchmarkEui: null,
  },
  {
    id: 'orbit',
    name: 'Orbit Tech Park',
    type: 'it',
    areaM2: 70000,
    baseKw: 220,
    plugKw: 380,
    lightKw: 150,
    hvacRatedKw: 650,
    K: 26,
    tau: 4,
    solarKwp: 600,
    batteryKwh: 800,
    batteryKw: 300,
    evSessionsCount: 60,
    comfortMin: 22,
    comfortMax: 26,
    daylightFraction: 0.5,
    m2PerPerson: 8,
    schedule: { startHour: 0, endHour: 24, is24h: true },
    benchmarkEui: null,
  },
  {
    id: 'meridian',
    name: 'Meridian Hotel',
    type: 'hotel',
    areaM2: 20000,
    baseKw: 90,
    plugKw: 120,
    lightKw: 70,
    hvacRatedKw: 300,
    K: 26,
    tau: 5,
    solarKwp: 150,
    batteryKwh: 0,
    batteryKw: 0,
    evSessionsCount: 16,
    comfortMin: 22,
    comfortMax: 26,
    daylightFraction: 0.2,
    m2PerPerson: 25,
    schedule: { startHour: 0, endHour: 24, is24h: true },
    benchmarkEui: null,
  },
];

export function getBuildingDesignPeakKw(b: BuildingDef): number {
  const evLimit = 0.6 * b.evSessionsCount * 7.4;
  return b.baseKw + b.plugKw + b.lightKw + b.hvacRatedKw + evLimit;
}
