import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Schneider Electric Exact Brand Palette */
        "schneider-green": "#009530",
        "bright-green": "#3DCD58",
        "seeding-green": "#9FAF00",
        black: "#000000",
        "dark-gray": "#262626",
        "se-dark-gray": "#626469",
        "light-gray": "#F2F2F2",
        "se-light-gray": "#9FA0A4",
        white: "#FFFFFF",
        "accent-yellow": "#FFD100",
        "accent-orange": "#E47F00",
        "accent-blue": "#42B4E6",
        "accent-red": "#B10043",

        /* 60–70% WHITE / LIGHT GRAY */
        surface: "#F2F2F2",
        "surface-dim": "#E5E7EB",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F8F9FA",
        "surface-container": "#F2F2F2",
        "surface-container-high": "#E2E4E8",
        "surface-container-highest": "#D1D5DB",

        /* 15–20% DARK / BLACK */
        "on-surface": "#262626",
        "on-surface-variant": "#626469",
        "inverse-surface": "#262626",
        "inverse-on-surface": "#FFFFFF",
        outline: "#626469",
        "outline-variant": "#9FA0A4",
        "surface-tint": "#009530",
        primary: "#000000",
        "on-primary": "#FFFFFF",

        /* 10–15% SCHNEIDER GREEN (#009530) */
        "primary-container": "#009530",
        "on-primary-container": "#FFFFFF",
        "inverse-primary": "#3DCD58",
        secondary: "#009530",
        "on-secondary": "#FFFFFF",

        /* 2–5% BRIGHT GREEN (#3DCD58) */
        "secondary-container": "#3DCD58",
        "on-secondary-container": "#000000",
        "secondary-fixed": "#3DCD58",
        "secondary-fixed-dim": "#009530",
        "on-secondary-fixed": "#000000",
        "on-secondary-fixed-variant": "#FFFFFF",

        /* <2% ACCENT COLORS (Yellow, Orange, Blue, Red, Seeding) */
        tertiary: "#FFD100",
        "on-tertiary": "#000000",
        "tertiary-container": "#FFF8D6",
        "on-tertiary-container": "#665200",
        "tertiary-fixed": "#FFD100",
        "tertiary-fixed-dim": "#E47F00",
        "on-tertiary-fixed": "#000000",
        "on-tertiary-fixed-variant": "#262626",
        error: "#B10043",
        "on-error": "#FFFFFF",
        "error-container": "#FDE8EF",
        "on-error-container": "#B10043",
        background: "#F2F2F2",
        "on-background": "#262626",
        "surface-variant": "#E2E4E8",

        /* Deterministic Engine Chart Series */
        series: {
          baseline: "#626469",
          thermos: "#009530",
          solar: "#9FAF00",
          battery: "#FFD100",
          grid: "#B10043",
          export: "#3DCD58",
          cooling: "#42B4E6",
          curtail: "#E47F00",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "sans-serif"],
        "display-hero": ["var(--font-inter)", "sans-serif"],
        "telemetry-xl": ["var(--font-jetbrains-mono)", "monospace"],
        "telemetry-md": ["var(--font-jetbrains-mono)", "monospace"],
        "telemetry-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "label-caps": ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "telemetry-xl": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "telemetry-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "500" }],
        "telemetry-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;
